"""
Core data structures and configuration management for PullData.

This module contains:
- Data classes (Document, Chunk, Embedding, Table, etc.)
- Configuration loading and validation
- Custom exceptions
"""

# Data types
from pulldata.core.datatypes import (
    Chunk,
    ChunkType,
    Document,
    DocumentType,
    Embedding,
    LLMResponse,
    OutputFormat,
    Project,
    QueryResult,
    RetrievedChunk,
    Table,
    TableCell,
)

# Configuration
from pulldata.core.config import (
    CacheConfig,
    Config,
    EmbedderConfig,
    FeatureFlags,
    GenerationConfig,
    LLMConfig,
    LoggingConfig,
    ModelConfig,
    ParsingConfig,
    PerformanceConfig,
    ProjectConfig,
    RetrievalConfig,
    StorageConfig,
    load_config,
    save_config,
)

# Exceptions
from pulldata.core.exceptions import (
    APIAuthenticationError,
    APIConnectionError,
    APIRateLimitError,
    CacheError,
    ChunkingError,
    ConfigError,
    ConfigFileNotFoundError,
    ConfigValidationError,
    DocumentNotFoundError,
    EmbedderLoadError,
    EmbeddingDimensionMismatchError,
    EmbeddingError,
    EmbeddingGenerationError,
    FileValidationError,
    FormatterNotFoundError,
    FormattingError,
    GenerationError,
    LLMInferenceError,
    LLMLoadError,
    LLMTimeoutError,
    ParsingError,
    PDFParsingError,
    ProjectNotFoundError,
    PromptTooLongError,
    PullDataError,
    RerankerError,
    RetrievalError,
    SchemaValidationError,
    SearchError,
    StorageConnectionError,
    StorageError,
    StorageInitializationError,
    StorageIntegrityError,
    StorageQueryError,
    SynthesisError,
    TableExtractionError,
    TemplateError,
    UnsupportedFormatError,
    ValidationError,
    VectorIndexError,
)

__all__ = [
    # Data types
    "Document",
    "DocumentType",
    "Chunk",
    "ChunkType",
    "Embedding",
    "Table",
    "TableCell",
    "QueryResult",
    "RetrievedChunk",
    "LLMResponse",
    "OutputFormat",
    "Project",
    # Configuration
    "Config",
    "StorageConfig",
    "ModelConfig",
    "EmbedderConfig",
    "LLMConfig",
    "GenerationConfig",
    "ParsingConfig",
    "RetrievalConfig",
    "CacheConfig",
    "ProjectConfig",
    "LoggingConfig",
    "PerformanceConfig",
    "FeatureFlags",
    "load_config",
    "save_config",
    # Exceptions
    "PullDataError",
    "ConfigError",
    "ConfigFileNotFoundError",
    "ConfigValidationError",
    "StorageError",
    "StorageConnectionError",
    "StorageInitializationError",
    "StorageQueryError",
    "StorageIntegrityError",
    "ProjectNotFoundError",
    "ParsingError",
    "DocumentNotFoundError",
    "UnsupportedFormatError",
    "PDFParsingError",
    "TableExtractionError",
    "ChunkingError",
    "EmbeddingError",
    "EmbedderLoadError",
    "EmbeddingGenerationError",
    "EmbeddingDimensionMismatchError",
    "RetrievalError",
    "VectorIndexError",
    "SearchError",
    "RerankerError",
    "GenerationError",
    "LLMLoadError",
    "LLMInferenceError",
    "LLMTimeoutError",
    "APIConnectionError",
    "APIAuthenticationError",
    "APIRateLimitError",
    "PromptTooLongError",
    "SynthesisError",
    "FormatterNotFoundError",
    "FormattingError",
    "TemplateError",
    "ValidationError",
    "SchemaValidationError",
    "FileValidationError",
    "CacheError",
]
